// Courtesy of https://twitter.com/lrgmnn/status/813635533658144768/
export const cards = [
  'Qmb1qt14iZwWrHh3Bz3Yd7JAvG5qXCLJVpYEsM822ASsC2',
  'QmWWAPiYXw2J7htipW1sBau42FkhmqvEkyaTCbv1dQope9',
  'QmcfbCXvaaAtxxzsBw2HFbMbzWgTEh2iwPH9xxc7zu2G93',
  'QmbD9eL4cAQVRtSU67y7zQeGkQnnHed7c3FcGT9kHUPr2r',
  'QmR54JGAFo6x4zGp5bTQgnd9MPa9kks2j6YTZja6LZjUkE',
  'QmXz1Qo8EgbEytM6SeY3dAmxyqpycixJswoB5md4Dk3UbN',
  'QmZXDW4DVfQJzoP6HKr3RvMP8E5RPTBTQpxVHDPCWZC3Wg',
  'QmWEFceEqH2BEdYgtoK2fYgqaRf5NeVi2qYWsqDCyDaiiS',
  'QmZQ2VTmrqjKtuTCJxH3S7CxpvrircpXpZ5a25gWPRJbJR',
  'QmQAy5Whae8HBGPp1DENgxPnNvKYewZATHNGaJsqB1QmnN',
  'QmYxRYdwFWfF8VTR3J3saM3PJKUaQpDCQ4azPDnbju62jK',
  'QmZKCt2J6ajiN3wQvS7rNxsWimo4KEzriTukA1pGynckaP',
  'QmcvapWR2ZcxuRyVPYhykfFS9oVprApC7tHBXoHCbWzjfw',
  'QmP4sPmPTtGcNpGVdwer9uMGSZZycix8P1WydRqo9dnjvf',
  'QmU3dtS1xntRoKo9bUUARPepoDhLmFLfmcpTGQ8ZtpM2W9',
  'QmZG3xhrw4d1xAxc9tnipgpFMhprKXcBjegJ75ZNibQwDc',
  'QmP9FTuCbAMCZrzFAgVxT3ttaSFGCdXM9pYa2v7i6CGMNN',
  'QmZa9dSjwunkiY2VsPrNTpUQcsSdS6gP5P43KoR4B1aSEq',
  'QmU76wYwuGVrHdX1CzUt9M9stpVfvzNCb4XVYc6jqtyPoY',
  'QmeDcJ7SWCRTvpjGJ8CNJopgSpZMfCsm14WMJJwJ5Mf9hb',
  'QmYPTrbo3V7eH4dSbSs415UwG3qknYd5ttNygNpNiLfKhY',
  'QmfJK132d6hVEuXM6j6xDwghwgcCDvxFPSkauw29qcDdmd',
];
// { cardName: 'Sleve McDichael', imgURI: '/image' },
// { cardName: 'Onson Sweemey', imageURI: '/image' },
// { cardName: 'Darryl Archideld', imageURI: '/image' },
// { cardName: 'Anatoli Smorin', imageURI: '/image' },
// { cardName: 'Rey McSriff', imageURI: '/image' },
// { cardName: 'Glenallen Mixon', imageURI: '/image' },
// { cardName: 'Mario McRlwain', imageURI: '/image' },
// { cardName: 'Raul Chamgerlain', imageURI: '/image' },
// { cardName: 'Kevin Nogilny', imageURI: '/image' },
// { cardName: 'Tony Smehrik', imageURI: '/image' },
// { cardName: 'Bobson Dugnutt', imageURI: '/image' },
// { cardName: 'Willie Dustice', imageURI: '/image' },
// { cardName: 'Jeromy Gride', imageURI: '/image' },
// { cardName: 'Scott Dourque', imageURI: '/image' },
// { cardName: 'Shown Furcotte', imageURI: '/image' },
// { cardName: 'Dean Wesrey', imageURI: '/image' },
// { cardName: 'Mike Truk', imageURI: '/image' },
// { cardName: 'Dwigt Rortugal', imageURI: '/image' },
// { cardName: 'Tim Sandaele', imageURI: '/image' },
// { cardName: 'Karl Dandleton', imageURI: '/image' },
// { cardName: 'Mike Sernandez', imageURI: '/image' },
// { cardName: 'Todd Bonzalez', imageURI: '/image' },
