// Courtesy of https://twitter.com/lrgmnn/status/813635533658144768/
export const cards = [
  {
    name: 'Sleve McDichael',
    image: 'Qmdss7xairE3ZHsosYnTWEdNWwtSWnPb5RAXYoAnswJyEE',
    description: '',
    id: 'Y_NL5JcWTZcBfLYImKTe1',
    creatorName: 'Agoric',
  },
  {
    name: 'Onson Sweemey',
    image: 'QmR3hn7JiKbDo544Yn2nLUxMWAAji5RPwNpFa9rJphXEf6',
    description: '',
    id: '4cCuxGrhmw1_ccYnuOIXk',
    creatorName: 'Agoric',
  },
  {
    name: 'Darryl Archideld',
    image: 'Qma3pJyJdvsb5io9iYHwxbS6Ro55CMSVxZUPvZ2w3y2A8b',
    description: '',
    id: 'ZnJ8MnhrMlYMkFcJk_pJP',
    creatorName: 'Agoric',
  },
  {
    name: 'Anatoli Smorin',
    image: 'QmcN5NAyN1sDc3Ap36W5Fxf5yuTCd9jamg9LQZr3CPa8os',
    description: '',
    id: 'fb8ApBtpIY1Ik9d62ZqFS',
    creatorName: 'Agoric',
  },
  {
    name: 'Rey McSriff',
    image: 'QmSZp8NyP9ubPSXySZnNTgjNxFdzoPk8ZtQvpLisAM5otf',
    description: '',
    id: 'J7NrtjDWJnXcbbVfTn7iG',
    creatorName: 'Agoric',
  },
  {
    name: 'Glenallen Mixon',
    image: 'QmNaJzu2JHF556pdwhUrDdR1cDhk3V59b8oEyFh73NUhrB',
    description: '',
    id: 's7DAbhpnkNT9i7CQluayu',
    creatorName: 'Agoric',
  },
  {
    name: 'Mario McRlwain',
    image: 'QmX8tw6ccjgnZFMaHUkZ7qrzy8VhLbgGR3LhY85fhcU6gp',
    description: '',
    id: 'SWZktd6MJdXDmEk4kIJJy',
    creatorName: 'Agoric',
  },
  {
    name: 'Raul Chamgerlain',
    image: 'QmcADqafzTBn7yZPXncfbB2wKJt5krWrNM2HWj83sMhoXP',
    description: '',
    id: 'O59Ai3x-b7lEMhl4so3_o',
    creatorName: 'Agoric',
  },
  {
    name: 'Kevin Nogilny',
    image: 'QmP2Wp657qAybDAygoyheakwhmZmLcbMnfSLfhnHYZoQbv',
    description: '',
    id: 'i4FaLQsA01znd2je8oN3A',
    creatorName: 'Agoric',
  },
  {
    name: 'Tony Smehrik',
    image: 'QmdLQR1CPJSRMwA48JB76r1GQUegGU15b3Er8VWzu9ANR4',
    description: '',
    id: 'lkkLb-56z1CyuR72oHZMO',
    creatorName: 'Agoric',
  },
  {
    name: 'Bobson Dugnutt',
    image: 'QmUJowUqWzdJMQvUdmXLiUDDCvcpXmQni84VfC9oSMFRA1',
    description: '',
    id: 'siY25XgERHG9d-lyvWuVr',
    creatorName: 'Agoric',
  },
  {
    name: 'Willie Dustice',
    image: 'QmYQQERCR26bBAwVcQCCd1qQQ6AmnQbVduRsNXtEEEihyk',
    description: '',
    id: '_Xcm35ezyWVcamNR3Fsjs',
    creatorName: 'Agoric',
  },
  {
    name: 'Jeromy Gride',
    image: 'QmSGa2XDLPeU3PMzAARRuM4VqGnE4SF4afNWqj2u1DMhnu',
    description: '',
    id: 'btr3X7g5Y7r6m_C89TfZE',
    creatorName: 'Agoric',
  },
  {
    name: 'Scott Dourque',
    image: 'QmaF3UMzqSPYDGeLEwyNNTeZbQoF5d8vmnYMKjhZmRea9t',
    description: '',
    id: '-sU2aSQdAZtSci73zx2Fe',
    creatorName: 'Agoric',
  },
  {
    name: 'Shown Furcotte',
    image: 'QmSSJDF2qtXmjaZPBGes8J3yNGLpUAuHehiJvpgYHix6L7',
    description: '',
    id: 'YTV_WxiTIa4gPP6tQ3cf-',
    creatorName: 'Agoric',
  },
  {
    name: 'Dean Wesrey',
    image: 'QmakTUsHQhkkjmNhqtoF7fUMVt5nYs59bHwgTitTX12EBn',
    description: '',
    id: '0aUIY6rlhca349WWI69q0',
    creatorName: 'Agoric',
  },
  {
    name: 'Mike Truk',
    image: 'QmadbBtD3qP6fPrip87sgTxenks7Jo73gtc6vBkRWogxQH',
    description: '',
    id: 'uELHUWCcHKCeZZ0oLMM4a',
    creatorName: 'Agoric',
  },
  {
    name: 'Dwigt Rortugal',
    image: 'QmSUsieCu3RufKSH1yPhYnPMvQsw7R9Jd5HPDfQhTcnAef',
    description: '',
    id: 'xcsBuacoyVTIRhxzRXTz6',
    creatorName: 'Agoric',
  },
  {
    name: 'Tim Sandaele',
    image: 'QmVvmFLeLhFcF6QFpHm8FZq7HLeS7DDUHYZCkXRcERfNkT',
    description: '',
    id: 'D6pzkXMH7n-0Jyp0DPw9S',
    creatorName: 'Agoric',
  },
  {
    name: 'Karl Dandleton',
    image: 'QmbCgaMexihvxZGzA7kTEv29ng3PMjR2qpVMmWY8XYrm7V',
    description: '',
    id: 'CT1K_gH4FMxFukWnhxmxh',
    creatorName: 'Agoric',
  },
  {
    name: 'Mike Sernandez',
    image: 'QmPxLLdzxtpgAMVGRSfDfdywiDYgfJFm2VPp1ZKS677jyC',
    description: '',
    id: '6M7lPzUtOF8aEiG5n0H4n',
    creatorName: 'Agoric',
  },
  {
    name: 'Todd Bonzalez',
    image: 'QmU3DY4kwJe4QoXaofwYk5coQzW1Zr49EbATPC53UpgDjS',
    description: '',
    id: 'YceDrXz8fjQUGs7PczbWK',
    creatorName: 'Agoric',
  },
];
